version: "3"
services: 
  app: # サービスの名前
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    tty: true
    ports:
      - 1323:1323
    volumes:
      - ./app:/go/src/app
    depends_on: 
      - mysql
  mysql:
    image: mysql:8.0
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    container_name: db-dev
    restart: always
    volumes:
      - data-dev:/var/lib/mysql

volumes:
  data-dev:
    driver: local